#ifndef __DEVICE_TYPES_H__
#define __DEVICE_TYPES_H__

#define DEVICE_TYPE_UNDEFINED			0x00
#define DEVICE_TYPE_RADIO				0x01
#define DEVICE_TYPE_IMU					0x02
#define DEVICE_TYPE_SERVO_CONTROLLER	0x03
#define DEVICE_TYPE_AOA					0x04

#endif